//
// Copyright 2022 Samsung
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//
// This source code is part of the near-RT RIC (RAN Intelligent Controller)
// platform project (RICP).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: node_config.proto

package entities

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NodeConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ComponentId:
	//	*NodeConfig_E2NodeComponentInterfaceTypeNG
	//	*NodeConfig_E2NodeComponentInterfaceTypeXn
	//	*NodeConfig_E2NodeComponentInterfaceTypeE1
	//	*NodeConfig_E2NodeComponentInterfaceTypeF1
	//	*NodeConfig_E2NodeComponentInterfaceTypeW1
	//	*NodeConfig_E2NodeComponentInterfaceTypeS1
	//	*NodeConfig_E2NodeComponentInterfaceTypeX2
	ComponentId             isNodeConfig_ComponentId `protobuf_oneof:"component_id"`
	ComponentType           string                   `protobuf:"bytes,8,opt,name=component_type,json=componentType,proto3" json:"component_type,omitempty"`
	ComponentConfigReqPart  []byte                   `protobuf:"bytes,9,opt,name=component_config_req_part,json=componentConfigReqPart,proto3" json:"component_config_req_part,omitempty"`
	ComponentConfigRespPart []byte                   `protobuf:"bytes,10,opt,name=component_config_resp_part,json=componentConfigRespPart,proto3" json:"component_config_resp_part,omitempty"`
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{0}
}

func (m *NodeConfig) GetComponentId() isNodeConfig_ComponentId {
	if m != nil {
		return m.ComponentId
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeNG() *E2NodeComponentInterfaceNG {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeNG); ok {
		return x.E2NodeComponentInterfaceTypeNG
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeXn() *E2NodeComponentInterfaceXn {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeXn); ok {
		return x.E2NodeComponentInterfaceTypeXn
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeE1() *E2NodeComponentInterfaceE1 {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeE1); ok {
		return x.E2NodeComponentInterfaceTypeE1
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeF1() *E2NodeComponentInterfaceF1 {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeF1); ok {
		return x.E2NodeComponentInterfaceTypeF1
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeW1() *E2NodeComponentInterfaceW1 {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeW1); ok {
		return x.E2NodeComponentInterfaceTypeW1
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeS1() *E2NodeComponentInterfaceS1 {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeS1); ok {
		return x.E2NodeComponentInterfaceTypeS1
	}
	return nil
}

func (x *NodeConfig) GetE2NodeComponentInterfaceTypeX2() *E2NodeComponentInterfaceX2 {
	if x, ok := x.GetComponentId().(*NodeConfig_E2NodeComponentInterfaceTypeX2); ok {
		return x.E2NodeComponentInterfaceTypeX2
	}
	return nil
}

func (x *NodeConfig) GetComponentType() string {
	if x != nil {
		return x.ComponentType
	}
	return ""
}

func (x *NodeConfig) GetComponentConfigReqPart() []byte {
	if x != nil {
		return x.ComponentConfigReqPart
	}
	return nil
}

func (x *NodeConfig) GetComponentConfigRespPart() []byte {
	if x != nil {
		return x.ComponentConfigRespPart
	}
	return nil
}

type isNodeConfig_ComponentId interface {
	isNodeConfig_ComponentId()
}

type NodeConfig_E2NodeComponentInterfaceTypeNG struct {
	E2NodeComponentInterfaceTypeNG *E2NodeComponentInterfaceNG `protobuf:"bytes,1,opt,name=e2nodeComponentInterfaceTypeNG,proto3,oneof"`
}

type NodeConfig_E2NodeComponentInterfaceTypeXn struct {
	E2NodeComponentInterfaceTypeXn *E2NodeComponentInterfaceXn `protobuf:"bytes,2,opt,name=e2nodeComponentInterfaceTypeXn,proto3,oneof"`
}

type NodeConfig_E2NodeComponentInterfaceTypeE1 struct {
	E2NodeComponentInterfaceTypeE1 *E2NodeComponentInterfaceE1 `protobuf:"bytes,3,opt,name=e2nodeComponentInterfaceTypeE1,proto3,oneof"`
}

type NodeConfig_E2NodeComponentInterfaceTypeF1 struct {
	E2NodeComponentInterfaceTypeF1 *E2NodeComponentInterfaceF1 `protobuf:"bytes,4,opt,name=e2nodeComponentInterfaceTypeF1,proto3,oneof"`
}

type NodeConfig_E2NodeComponentInterfaceTypeW1 struct {
	E2NodeComponentInterfaceTypeW1 *E2NodeComponentInterfaceW1 `protobuf:"bytes,5,opt,name=e2nodeComponentInterfaceTypeW1,proto3,oneof"`
}

type NodeConfig_E2NodeComponentInterfaceTypeS1 struct {
	E2NodeComponentInterfaceTypeS1 *E2NodeComponentInterfaceS1 `protobuf:"bytes,6,opt,name=e2nodeComponentInterfaceTypeS1,proto3,oneof"`
}

type NodeConfig_E2NodeComponentInterfaceTypeX2 struct {
	E2NodeComponentInterfaceTypeX2 *E2NodeComponentInterfaceX2 `protobuf:"bytes,7,opt,name=e2nodeComponentInterfaceTypeX2,proto3,oneof"`
}

func (*NodeConfig_E2NodeComponentInterfaceTypeNG) isNodeConfig_ComponentId() {}

func (*NodeConfig_E2NodeComponentInterfaceTypeXn) isNodeConfig_ComponentId() {}

func (*NodeConfig_E2NodeComponentInterfaceTypeE1) isNodeConfig_ComponentId() {}

func (*NodeConfig_E2NodeComponentInterfaceTypeF1) isNodeConfig_ComponentId() {}

func (*NodeConfig_E2NodeComponentInterfaceTypeW1) isNodeConfig_ComponentId() {}

func (*NodeConfig_E2NodeComponentInterfaceTypeS1) isNodeConfig_ComponentId() {}

func (*NodeConfig_E2NodeComponentInterfaceTypeX2) isNodeConfig_ComponentId() {}

type E2NodeComponentInterfaceNG struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AmfName string `protobuf:"bytes,11,opt,name=amf_name,json=amfName,proto3" json:"amf_name,omitempty"`
}

func (x *E2NodeComponentInterfaceNG) Reset() {
	*x = E2NodeComponentInterfaceNG{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceNG) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceNG) ProtoMessage() {}

func (x *E2NodeComponentInterfaceNG) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceNG.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceNG) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{1}
}

func (x *E2NodeComponentInterfaceNG) GetAmfName() string {
	if x != nil {
		return x.AmfName
	}
	return ""
}

type E2NodeComponentInterfaceXn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to GlobalNgRanNodeId:
	//	*E2NodeComponentInterfaceXn_GlobalNgenbId
	//	*E2NodeComponentInterfaceXn_GlobalGnbId
	GlobalNgRanNodeId isE2NodeComponentInterfaceXn_GlobalNgRanNodeId `protobuf_oneof:"global_ng_ran_node_id"`
}

func (x *E2NodeComponentInterfaceXn) Reset() {
	*x = E2NodeComponentInterfaceXn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceXn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceXn) ProtoMessage() {}

func (x *E2NodeComponentInterfaceXn) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceXn.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceXn) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{2}
}

func (m *E2NodeComponentInterfaceXn) GetGlobalNgRanNodeId() isE2NodeComponentInterfaceXn_GlobalNgRanNodeId {
	if m != nil {
		return m.GlobalNgRanNodeId
	}
	return nil
}

func (x *E2NodeComponentInterfaceXn) GetGlobalNgenbId() *GlobalNGENBID {
	if x, ok := x.GetGlobalNgRanNodeId().(*E2NodeComponentInterfaceXn_GlobalNgenbId); ok {
		return x.GlobalNgenbId
	}
	return nil
}

func (x *E2NodeComponentInterfaceXn) GetGlobalGnbId() *GlobalGNBID {
	if x, ok := x.GetGlobalNgRanNodeId().(*E2NodeComponentInterfaceXn_GlobalGnbId); ok {
		return x.GlobalGnbId
	}
	return nil
}

type isE2NodeComponentInterfaceXn_GlobalNgRanNodeId interface {
	isE2NodeComponentInterfaceXn_GlobalNgRanNodeId()
}

type E2NodeComponentInterfaceXn_GlobalNgenbId struct {
	GlobalNgenbId *GlobalNGENBID `protobuf:"bytes,12,opt,name=global_ngenb_id,json=globalNgenbId,proto3,oneof"`
}

type E2NodeComponentInterfaceXn_GlobalGnbId struct {
	GlobalGnbId *GlobalGNBID `protobuf:"bytes,13,opt,name=global_gnb_id,json=globalGnbId,proto3,oneof"`
}

func (*E2NodeComponentInterfaceXn_GlobalNgenbId) isE2NodeComponentInterfaceXn_GlobalNgRanNodeId() {}

func (*E2NodeComponentInterfaceXn_GlobalGnbId) isE2NodeComponentInterfaceXn_GlobalNgRanNodeId() {}

type E2NodeComponentInterfaceE1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GNBCuCpId int64 `protobuf:"varint,14,opt,name=gNB_cu_cp_id,json=gNBCuCpId,proto3" json:"gNB_cu_cp_id,omitempty"`
}

func (x *E2NodeComponentInterfaceE1) Reset() {
	*x = E2NodeComponentInterfaceE1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceE1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceE1) ProtoMessage() {}

func (x *E2NodeComponentInterfaceE1) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceE1.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceE1) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{3}
}

func (x *E2NodeComponentInterfaceE1) GetGNBCuCpId() int64 {
	if x != nil {
		return x.GNBCuCpId
	}
	return 0
}

type E2NodeComponentInterfaceF1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GNBDuId int64 `protobuf:"varint,15,opt,name=gNB_du_id,json=gNBDuId,proto3" json:"gNB_du_id,omitempty"`
}

func (x *E2NodeComponentInterfaceF1) Reset() {
	*x = E2NodeComponentInterfaceF1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceF1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceF1) ProtoMessage() {}

func (x *E2NodeComponentInterfaceF1) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceF1.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceF1) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{4}
}

func (x *E2NodeComponentInterfaceF1) GetGNBDuId() int64 {
	if x != nil {
		return x.GNBDuId
	}
	return 0
}

type E2NodeComponentInterfaceW1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NgenbDuId int64 `protobuf:"varint,16,opt,name=ngenb_du_id,json=ngenbDuId,proto3" json:"ngenb_du_id,omitempty"`
}

func (x *E2NodeComponentInterfaceW1) Reset() {
	*x = E2NodeComponentInterfaceW1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceW1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceW1) ProtoMessage() {}

func (x *E2NodeComponentInterfaceW1) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceW1.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceW1) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{5}
}

func (x *E2NodeComponentInterfaceW1) GetNgenbDuId() int64 {
	if x != nil {
		return x.NgenbDuId
	}
	return 0
}

type E2NodeComponentInterfaceS1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MmeName string `protobuf:"bytes,17,opt,name=mme_name,json=mmeName,proto3" json:"mme_name,omitempty"`
}

func (x *E2NodeComponentInterfaceS1) Reset() {
	*x = E2NodeComponentInterfaceS1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceS1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceS1) ProtoMessage() {}

func (x *E2NodeComponentInterfaceS1) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceS1.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceS1) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{6}
}

func (x *E2NodeComponentInterfaceS1) GetMmeName() string {
	if x != nil {
		return x.MmeName
	}
	return ""
}

type E2NodeComponentInterfaceX2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GlobalEnbId   *GlobalENBID   `protobuf:"bytes,18,opt,name=global_enb_id,json=globalEnbId,proto3" json:"global_enb_id,omitempty"`
	GlobalEngnbId *GlobalENGNBID `protobuf:"bytes,19,opt,name=global_engnb_id,json=globalEngnbId,proto3" json:"global_engnb_id,omitempty"`
}

func (x *E2NodeComponentInterfaceX2) Reset() {
	*x = E2NodeComponentInterfaceX2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *E2NodeComponentInterfaceX2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*E2NodeComponentInterfaceX2) ProtoMessage() {}

func (x *E2NodeComponentInterfaceX2) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use E2NodeComponentInterfaceX2.ProtoReflect.Descriptor instead.
func (*E2NodeComponentInterfaceX2) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{7}
}

func (x *E2NodeComponentInterfaceX2) GetGlobalEnbId() *GlobalENBID {
	if x != nil {
		return x.GlobalEnbId
	}
	return nil
}

func (x *E2NodeComponentInterfaceX2) GetGlobalEngnbId() *GlobalENGNBID {
	if x != nil {
		return x.GlobalEngnbId
	}
	return nil
}

type GlobalENBID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlmnIdentity string `protobuf:"bytes,20,opt,name=plmn_identity,json=plmnIdentity,proto3" json:"plmn_identity,omitempty"`
	EnbId        string `protobuf:"bytes,21,opt,name=enb_id,json=enbId,proto3" json:"enb_id,omitempty"`
}

func (x *GlobalENBID) Reset() {
	*x = GlobalENBID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalENBID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalENBID) ProtoMessage() {}

func (x *GlobalENBID) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalENBID.ProtoReflect.Descriptor instead.
func (*GlobalENBID) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{8}
}

func (x *GlobalENBID) GetPlmnIdentity() string {
	if x != nil {
		return x.PlmnIdentity
	}
	return ""
}

func (x *GlobalENBID) GetEnbId() string {
	if x != nil {
		return x.EnbId
	}
	return ""
}

type GlobalENGNBID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlmnIdentity string `protobuf:"bytes,22,opt,name=plmn_identity,json=plmnIdentity,proto3" json:"plmn_identity,omitempty"`
	GnbId        string `protobuf:"bytes,23,opt,name=gnb_id,json=gnbId,proto3" json:"gnb_id,omitempty"`
}

func (x *GlobalENGNBID) Reset() {
	*x = GlobalENGNBID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalENGNBID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalENGNBID) ProtoMessage() {}

func (x *GlobalENGNBID) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalENGNBID.ProtoReflect.Descriptor instead.
func (*GlobalENGNBID) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{9}
}

func (x *GlobalENGNBID) GetPlmnIdentity() string {
	if x != nil {
		return x.PlmnIdentity
	}
	return ""
}

func (x *GlobalENGNBID) GetGnbId() string {
	if x != nil {
		return x.GnbId
	}
	return ""
}

type GlobalGNBID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlmnIdentity string `protobuf:"bytes,24,opt,name=plmn_identity,json=plmnIdentity,proto3" json:"plmn_identity,omitempty"`
	GnbId        string `protobuf:"bytes,25,opt,name=gnb_id,json=gnbId,proto3" json:"gnb_id,omitempty"`
}

func (x *GlobalGNBID) Reset() {
	*x = GlobalGNBID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalGNBID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalGNBID) ProtoMessage() {}

func (x *GlobalGNBID) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalGNBID.ProtoReflect.Descriptor instead.
func (*GlobalGNBID) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalGNBID) GetPlmnIdentity() string {
	if x != nil {
		return x.PlmnIdentity
	}
	return ""
}

func (x *GlobalGNBID) GetGnbId() string {
	if x != nil {
		return x.GnbId
	}
	return ""
}

type GlobalNGENBID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlmnIdentity string `protobuf:"bytes,26,opt,name=plmn_identity,json=plmnIdentity,proto3" json:"plmn_identity,omitempty"`
	EnbId        string `protobuf:"bytes,27,opt,name=enb_id,json=enbId,proto3" json:"enb_id,omitempty"`
}

func (x *GlobalNGENBID) Reset() {
	*x = GlobalNGENBID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_config_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalNGENBID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalNGENBID) ProtoMessage() {}

func (x *GlobalNGENBID) ProtoReflect() protoreflect.Message {
	mi := &file_node_config_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalNGENBID.ProtoReflect.Descriptor instead.
func (*GlobalNGENBID) Descriptor() ([]byte, []int) {
	return file_node_config_proto_rawDescGZIP(), []int{11}
}

func (x *GlobalNGENBID) GetPlmnIdentity() string {
	if x != nil {
		return x.PlmnIdentity
	}
	return ""
}

func (x *GlobalNGENBID) GetEnbId() string {
	if x != nil {
		return x.EnbId
	}
	return ""
}

var File_node_config_proto protoreflect.FileDescriptor

var file_node_config_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0xcb, 0x07,
	0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x47, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x47, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x47, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x58, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x58, 0x6e, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x58, 0x6e, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x31, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x45, 0x31, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x45, 0x31, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x31, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x46, 0x31, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x46, 0x31, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x57, 0x31, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x57, 0x31, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x57, 0x31, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x31, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x31, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x31, 0x12, 0x6e, 0x0a, 0x1e,
	0x65, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x58, 0x32, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x58, 0x32, 0x48, 0x00, 0x52, 0x1e, 0x65, 0x32,
	0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x58, 0x32, 0x12, 0x25, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x70, 0x61, 0x72, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x16, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x50, 0x61, 0x72, 0x74, 0x12, 0x3b,
	0x0a, 0x1a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x50, 0x61, 0x72, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x1a, 0x45,
	0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x4e, 0x47, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6d, 0x66,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6d, 0x66,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x1a, 0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x58, 0x6e, 0x12, 0x41, 0x0a, 0x0f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x6e, 0x67,
	0x65, 0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4e, 0x47,
	0x45, 0x4e, 0x42, 0x49, 0x44, 0x48, 0x00, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x4e,
	0x67, 0x65, 0x6e, 0x62, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x5f, 0x67, 0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x47,
	0x4e, 0x42, 0x49, 0x44, 0x48, 0x00, 0x52, 0x0b, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x47, 0x6e,
	0x62, 0x49, 0x64, 0x42, 0x17, 0x0a, 0x15, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x6e, 0x67,
	0x5f, 0x72, 0x61, 0x6e, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x22, 0x3d, 0x0a, 0x1a,
	0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x45, 0x31, 0x12, 0x1f, 0x0a, 0x0c, 0x67, 0x4e,
	0x42, 0x5f, 0x63, 0x75, 0x5f, 0x63, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x67, 0x4e, 0x42, 0x43, 0x75, 0x43, 0x70, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x1a, 0x45,
	0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x46, 0x31, 0x12, 0x1a, 0x0a, 0x09, 0x67, 0x4e, 0x42,
	0x5f, 0x64, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x4e,
	0x42, 0x44, 0x75, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x1a, 0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x57, 0x31, 0x12, 0x1e, 0x0a, 0x0b, 0x6e, 0x67, 0x65, 0x6e, 0x62, 0x5f, 0x64, 0x75, 0x5f,
	0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x67, 0x65, 0x6e, 0x62, 0x44,
	0x75, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x1a, 0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53,
	0x31, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x98, 0x01, 0x0a,
	0x1a, 0x45, 0x32, 0x6e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x58, 0x32, 0x12, 0x39, 0x0a, 0x0d, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x12, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x45, 0x4e, 0x42, 0x49, 0x44, 0x52, 0x0b, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x45, 0x6e, 0x62, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x0f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x5f, 0x65, 0x6e, 0x67, 0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x45, 0x4e, 0x47, 0x4e, 0x42, 0x49, 0x44, 0x52, 0x0d, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x45, 0x6e, 0x67, 0x6e, 0x62, 0x49, 0x64, 0x22, 0x49, 0x0a, 0x0b, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x45, 0x4e, 0x42, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x6d, 0x6e, 0x5f, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70,
	0x6c, 0x6d, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x62,
	0x49, 0x64, 0x22, 0x4b, 0x0a, 0x0d, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x4e, 0x47, 0x4e,
	0x42, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x6c, 0x6d, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x6d, 0x6e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x6e, 0x62, 0x5f,
	0x69, 0x64, 0x18, 0x17, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x6e, 0x62, 0x49, 0x64, 0x22,
	0x49, 0x0a, 0x0b, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x47, 0x4e, 0x42, 0x49, 0x44, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x6c, 0x6d, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x18, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x6d, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x67, 0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x19, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x67, 0x6e, 0x62, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x0d, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x4e, 0x47, 0x45, 0x4e, 0x42, 0x49, 0x44, 0x12, 0x23, 0x0a, 0x0d, 0x70,
	0x6c, 0x6d, 0x6e, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x1a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x70, 0x6c, 0x6d, 0x6e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x1b, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6e, 0x62, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_config_proto_rawDescOnce sync.Once
	file_node_config_proto_rawDescData = file_node_config_proto_rawDesc
)

func file_node_config_proto_rawDescGZIP() []byte {
	file_node_config_proto_rawDescOnce.Do(func() {
		file_node_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_config_proto_rawDescData)
	})
	return file_node_config_proto_rawDescData
}

var file_node_config_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_node_config_proto_goTypes = []interface{}{
	(*NodeConfig)(nil),                 // 0: entities.NodeConfig
	(*E2NodeComponentInterfaceNG)(nil), // 1: entities.E2nodeComponentInterfaceNG
	(*E2NodeComponentInterfaceXn)(nil), // 2: entities.E2nodeComponentInterfaceXn
	(*E2NodeComponentInterfaceE1)(nil), // 3: entities.E2nodeComponentInterfaceE1
	(*E2NodeComponentInterfaceF1)(nil), // 4: entities.E2nodeComponentInterfaceF1
	(*E2NodeComponentInterfaceW1)(nil), // 5: entities.E2nodeComponentInterfaceW1
	(*E2NodeComponentInterfaceS1)(nil), // 6: entities.E2nodeComponentInterfaceS1
	(*E2NodeComponentInterfaceX2)(nil), // 7: entities.E2nodeComponentInterfaceX2
	(*GlobalENBID)(nil),                // 8: entities.GlobalENBID
	(*GlobalENGNBID)(nil),              // 9: entities.GlobalENGNBID
	(*GlobalGNBID)(nil),                // 10: entities.GlobalGNBID
	(*GlobalNGENBID)(nil),              // 11: entities.GlobalNGENBID
}
var file_node_config_proto_depIdxs = []int32{
	1,  // 0: entities.NodeConfig.e2nodeComponentInterfaceTypeNG:type_name -> entities.E2nodeComponentInterfaceNG
	2,  // 1: entities.NodeConfig.e2nodeComponentInterfaceTypeXn:type_name -> entities.E2nodeComponentInterfaceXn
	3,  // 2: entities.NodeConfig.e2nodeComponentInterfaceTypeE1:type_name -> entities.E2nodeComponentInterfaceE1
	4,  // 3: entities.NodeConfig.e2nodeComponentInterfaceTypeF1:type_name -> entities.E2nodeComponentInterfaceF1
	5,  // 4: entities.NodeConfig.e2nodeComponentInterfaceTypeW1:type_name -> entities.E2nodeComponentInterfaceW1
	6,  // 5: entities.NodeConfig.e2nodeComponentInterfaceTypeS1:type_name -> entities.E2nodeComponentInterfaceS1
	7,  // 6: entities.NodeConfig.e2nodeComponentInterfaceTypeX2:type_name -> entities.E2nodeComponentInterfaceX2
	11, // 7: entities.E2nodeComponentInterfaceXn.global_ngenb_id:type_name -> entities.GlobalNGENBID
	10, // 8: entities.E2nodeComponentInterfaceXn.global_gnb_id:type_name -> entities.GlobalGNBID
	8,  // 9: entities.E2nodeComponentInterfaceX2.global_enb_id:type_name -> entities.GlobalENBID
	9,  // 10: entities.E2nodeComponentInterfaceX2.global_engnb_id:type_name -> entities.GlobalENGNBID
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_node_config_proto_init() }
func file_node_config_proto_init() {
	if File_node_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceNG); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceXn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceE1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceF1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceW1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceS1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*E2NodeComponentInterfaceX2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalENBID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalENGNBID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalGNBID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_config_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalNGENBID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_node_config_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*NodeConfig_E2NodeComponentInterfaceTypeNG)(nil),
		(*NodeConfig_E2NodeComponentInterfaceTypeXn)(nil),
		(*NodeConfig_E2NodeComponentInterfaceTypeE1)(nil),
		(*NodeConfig_E2NodeComponentInterfaceTypeF1)(nil),
		(*NodeConfig_E2NodeComponentInterfaceTypeW1)(nil),
		(*NodeConfig_E2NodeComponentInterfaceTypeS1)(nil),
		(*NodeConfig_E2NodeComponentInterfaceTypeX2)(nil),
	}
	file_node_config_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*E2NodeComponentInterfaceXn_GlobalNgenbId)(nil),
		(*E2NodeComponentInterfaceXn_GlobalGnbId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_config_proto_goTypes,
		DependencyIndexes: file_node_config_proto_depIdxs,
		MessageInfos:      file_node_config_proto_msgTypes,
	}.Build()
	File_node_config_proto = out.File
	file_node_config_proto_rawDesc = nil
	file_node_config_proto_goTypes = nil
	file_node_config_proto_depIdxs = nil
}
